version: '3.3'
services:
  mysql_database:
    image: mysql:8.0.19
    container_name: mysql
    ports:
      - '3306:3306'
    volumes:
      - ./mysql:/var/lib/mysql:rw
    command: mysqld --sql_mode=""
    environment:
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - dev_env
    restart: always
  MailDev:
    image: maildev/maildev
    container_name: MailDev
    ports:
      - '1080:80'
    environment:
      - MAILDEV_SMTP_PORT=25
    networks:
      - dev_env
    restart: always
  php:
    build: .
    container_name: php
    depends_on:
      - mysql_database
      - MailDev
    ports: 
      - '80:80'
      - '443:443'
    volumes:
      - ./php:/var/www/html
      - ./logs:/var/log/
    environment:
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - TZ=Europe/Paris
    networks:
      - dev_env
    links:
      - mysql_database:db
      - MailDev:MailDev
      - postgre_sql:postgres
  PMA:
    image: phpmyadmin/phpmyadmin
    container_name: phpMyAdmin
    depends_on:
      - mysql_database
    environment:
      - PMA_ARBITRARY=1
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
    ports:
      - '8090:80'
    networks:
      - dev_env
    links:
      - mysql_database:db
  postgre_sql:
    image: postgres:13.2
    container_name: postgres
    ports:
        - '5432:5432'
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw
    environment:
        - POSTGRES_USER=root
        - POSTGRES_PASSWORD=root
    restart: always
    networks:
      - dev_env
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    volumes:
      - ./pgadmin/servers.json:/pgadmin4/servers.json:rw
      - ./pgadmin/lib:/var/lib/pgadmin
    environment:
        - PGADMIN_DEFAULT_EMAIL=root
        - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - '8100:80'
    links:
      - postgre_sql:postgres
    restart: always
    networks:
      - dev_env

networks:
  dev_env:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
